version: '3.8'

services:
  web:
    build: .
    container_name: aisexter_web_prod
    command: gunicorn AIsexter.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=False
    networks:
      - aisexter_network

  nginx:
    image: nginx:alpine
    container_name: aisexter_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - aisexter_network

volumes:
  static_volume:
  media_volume:

networks:
  aisexter_network:
    driver: bridge

